### ISSUE TITLE
why express-cluster run this 'console' out of cluster() many times?

### ISSUE THREAD

**Issue by Naixor** [Flipboard/express-cluster#3]
```JavaScript
var cluster = require('express-cluster');
console.log(1); // This code run at first, then it run another four times.(my computer have 4 cpus)
cluster(function() {
	var app = require('../app');
	app.set('port', process.env.PORT || 3000);
	var server = app.listen(app.get('port'), function() {
		log.info('Express server listening on port ', server.address().port, " with pid ", process.pid );
	});
});
```

**Comment by eden** [comment]
This happens because the process is forked `n` times where `n` is the number of workers cluster decides to startup. When a fork happens, any code that runs before the fork will run in each subprocess. You can avoid this by putting any initialization code that should only happen in the master in an if statement blocked on `process.env.NODE_UNIQUE_ID` being undefined. For example:

```javascript
if (!process.env.NODE_UNIQUE_ID) {
  // master code
}
cluster(function() {
  // ...
});

**Comment by eden** [comment]
As this isn't a problem with the module, I'm closing this issue. Let me know if you have other questions.
