### ISSUE TITLE
increase default worker count by 1

### ISSUE THREAD

**Issue by blitmap** [Flipboard/express-cluster#8]
Hello hello - I see that in express-cluster if process.env.WORKER_COUNT is not defined it assumes the number of workers should be: os.cpus().length

I am used to seeing: os.cpus().length + 1

I'm not exactly sure why this is.  I've been told that on a dual-core processor without hyperthreading (2 execution threads) it is ideal to have 3 workers so the application appropriately saturates the scheduler.  This doesn't really make sense to me, but it sounds like a poor mans' way of controlling thread/process affinity.  I guess the idea is to make sure the clustered app as a whole stays responsive enough as a worker count equal to the number of cores is moderately starved by the rest of the system (other processes) being scheduled across the CPU.

The most correct answer is to probably measure and adjust as needed and just set WORKER_COUNT.

Anyway, I'm filing this because I just thought os.cpus().length + 1 was the more traditional default.  I leave it up to you, of course :-)

**Comment by eden** [comment]
It's hard to have a default that applies to all situations because we don't know what callers are going to do with their workers. `os.cpus().length` or `os.cpus().length + 1` are both sane defaults and it's not entirely clear that adding one will help if every worker has the potential to saturate the CPU in the same way.

The node cluster docs use `os.cpus().length` in their example, so we use it as the default. I'll update the README to clarify.
